#!/usr/bin/env python
# Maintainer Dan Pilch <dan@ctrlengineering.com>
# Description: Upload music to Google Music Lazily
# -*- encoding: utf8 -*-

from gmusicapi import Musicmanager
import argparse
import sys
import os

# Set encoding to utf8 to fix filename encodings
reload(sys)
sys.setdefaultencoding('utf8')

class GoogleMusicUpload(object):
    def __init__(self):
        self.wanted_filetypes = ('.mp3', '.flac')
        self.cwd = os.getcwd()
        self.client = Musicmanager()
        self.client.login()
        
    def upload(self, files):
        if len(files) >= 1:
            for f in files:
                try:
                    self.client.upload(f, transcode_quality="320k", enable_matching=True)
                except Exception as e:
                    pass
                print "Uploaded: {0}".format(str(f))
        else:
            print "No files to upload"

    def authenticate(self):
        from gmusicapi import Mobileclient
        from getpass import getpass
        
        self.client.perform_oauth()

    def find_music(self, recurse):
        
        # Recursively look for files in subdirectories... Respect, walk \m/
        if recurse:
            found_files = []
            for root, dirs, files in os.walk(self.cwd):
                for f in files:
                    if f.endswith(self.wanted_filetypes):
                        found_files.append(os.path.join(root, str(f)))

        else:
            # Just look in the current directory
            found_files = [each for each in os.listdir(self.cwd) if each.endswith(self.wanted_filetypes)]
        
        return found_files

def main():
    parser = argparse.ArgumentParser(description="Upload music to Google Play Music")
    parser.add_argument('--authenticate', '-a', help="Perform OAuth request for Google auth", action="store_true", required=False, default=None)
    parser.add_argument('--recurse', '-r', help="Recursively look for music in all directories", action="store_true", required=False, default=None)
    args = parser.parse_args()

    run = GoogleMusicUpload()

    if args.authenticate:
        run.authenticate()

    run.upload(run.find_music(args.recurse))

if __name__ == "__main__":
    main()
